.libPaths("/home/shinichi/workspace/lalab/___system/rlib")
if (!require("readr")) install.packages("readr")
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("eeptools")) install.packages("eeptools")
if (!require("stringr")) install.packages("stringr")
if (!require("Hmisc")) install.packages("Hmisc")
if (!require("haven")) install.packages("haven")
if (!require("rmatio")) install.packages("rmatio")
if (!require("foreign")) install.packages("foreign")
if (!require("chron")) install.packages("chron")
if (!require("plyr")) install.packages("plyr")
if (!require("car")) install.packages("car")
if (!require("qqplotr")) install.packages("qqplotr")
if (!require("R.matlab")) install.packages("R.matlab")
if (!require("matrixStats")) install.packages("matrixStats")
if (!require("MASS")) install.packages("MASS")
if (!require("R.utils")) install.packages("R.utils")

library(readr)
library(tidyverse)
library(ggplot2)
library(eeptools)
library(stringr)
library(Hmisc)
library(haven)
library(rmatio)
library(foreign)
library(chron)
library(plyr)
library(car)
library(qqplotr)
library(devtools)
library(roxygen2)
library(R.matlab)
library(matrixStats)
library(MASS)
library(R.utils)
library(Rcpp)
library(RcppArmadillo)
library(lar)
library(larcpp)



adj <- read.csv("/home/shinichi/Eclipse/data/data/adj.csv")
save_data(adj,"adj","/home/shinichi/workspace/lalab/___project/test/Datasource/___datasets/adj")

anti <- read.csv("/home/shinichi/Eclipse/data/data/anti.csv")
save_data(anti,"anti","/home/shinichi/workspace/lalab/___project/test/Datasource/___datasets/anti")

bld <- read.csv("/home/shinichi/Eclipse/data/data/bld.csv")
save_data(bld,"bld","/home/shinichi/workspace/lalab/___project/test/Datasource/___datasets/bld")

bldef <- read.csv("/home/shinichi/Eclipse/data/data/bldef.csv")
save_data(bldef,"bldef","/home/shinichi/workspace/lalab/___project/test/Datasource/___datasets/bldef")

demog <- read.csv("/home/shinichi/Eclipse/data/data/demog.csv")
save_data(demog,"demog","/home/shinichi/workspace/lalab/___project/test/Datasource/___datasets/demog")

saveRDS(c(1), file="/home/shinichi/workspace/lalab/___system/___user/shinichi/end/_end.R")


