.libPaths("/home/shinichi/workspace/___system/rlib")

if (!require("readr")) install.packages("readr")
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("eeptools")) install.packages("eeptools")
if (!require("stringr")) install.packages("stringr")
if (!require("Hmisc")) install.packages("Hmisc")
if (!require("haven")) install.packages("haven")
if (!require("rmatio")) install.packages("rmatio")
if (!require("foreign")) install.packages("foreign")
if (!require("chron")) install.packages("chron")
if (!require("plyr")) install.packages("plyr")
if (!require("car")) install.packages("car")
if (!require("qqplotr")) install.packages("qqplotr")
if (!require("R.matlab")) install.packages("R.matlab")

library(readr)
library(tidyverse)
library(ggplot2)
library(eeptools)
library(stringr)
library(Hmisc)
library(haven)
library(rmatio)
library(foreign)
library(chron)
library(plyr)
library(car)
library(qqplotr)
library(devtools)
library(roxygen2)
library(R.matlab)
library(matrixStats)
library(MASS)
library(R.utils)
library(Rcpp)
library(RcppArmadillo)
library(lar)
library(larcpp)

